baseurl = "/"
languageCode = "en-us"
title = "SNA for Social Sciences"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Welcome"
    url = "/Welcome/"
    weight = 1
[[menu.main]]
    name = "Week 1 - dyads"
    url = "/dyads/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/JochemTolsma/SNtest.git"


[params]
    description = "Social Networks, dyads, egocentric, sociocentric"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

